name: Daily Deployment

on:
  schedule:
    # Schedule the job to run at 3 AM EST every day (8 AM UTC)
    - cron: '0 8 * * *'
  
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      deploy:
        description: "Manually trigger deployment"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Trigger a Vercel redeploy using the Vercel CLI or API
      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
